using Microsoft.AspNetCore.Mvc;
using Microsoft.Playwright;

namespace TipTapTest.Server.Controllers;


[ApiController]
[Route("api/[controller]")]

public class PdfController : ControllerBase
{
    private readonly IPlaywright _playwright;

    public PdfController(IPlaywright playwright)
    {
        _playwright = playwright;
    }
    
    [HttpPost("DownloadPdf")]
    public async Task<IActionResult> DownloadPDf([FromBody] string htmlContent)
    {
        var browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = true });
        var page = await browser.NewPageAsync();
        
        await page.SetContentAsync(htmlContent);
        string css = @"
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }
            p{
                color: blue;
            }
        ";
        await page.AddStyleTagAsync(new PageAddStyleTagOptions { Content = css });

        var pdf = await page.PdfAsync(new PagePdfOptions
        {
            Format = "A4",
            DisplayHeaderFooter = true,
            FooterTemplate = @"
            <div style='width: 100%; text-align: center; font-size: 10px;'>
                <span style='float: left;'>Generated by MyApp</span>
                <span style='float: right;'>Page <span class='pageNumber'></span> of <span class='totalPages'></span></span>
            </div>",
            HeaderTemplate = "<div style='text-align: center; font-size: 12px;'>Header Content</div>", 
        });
        
        return File(pdf, "application/pdf", "generatedPdf.pdf");
    }
}